# Data Paths
data:
  csv_file: datasets/players.csv
  models_dir: models

# Flask App
flask:
  host: '0.0.0.0'
  debug: true
  port: 5001

# Model Training
model_training:
  xgboost:
    learning_rate: 0.1
    max_depth: 3
    subsample: 0.8
    colsample_bytree: 0.8
    n_estimators: 100
    alpha: 0.1
    lambda: 0.1
  neural_network:
    input_size: 32
    hidden_layers:
      - size: 128
        activation: relu
      - size: 64
        activation: relu
    output_layer:
      size: 1
    n_epochs: 10
    learning_rate: 0.001

# Optimization Constraints
optimization:
  max_budget: 1000
  max_players:
    keepers: 2
    defenders: 5
    midfielders: 5
    forwards: 3

# Visualization
visualization:
  output_dir: visualizations
